package rules
import com.ftn.sbnz.model.models.TrafficDensity;
import com.ftn.sbnz.model.models.TrafficAction;
import com.ftn.sbnz.model.models.Notification;
import com.ftn.sbnz.model.models.PedestrianDetected;
import com.ftn.sbnz.model.models.Accident;
import com.ftn.sbnz.model.models.IllegalParking;
import com.ftn.sbnz.model.models.TimeOfDay;

rule "Rush rour - extend the green light"
when 
    $t : TrafficDensity($c : crossroad, value > 70)
    TimeOfDay($h : hour,  $h >= 7 && $h <= 9)
then 
    insert(new TrafficAction($c, "extendGreen", 30));
    Notification n1 = new Notification("Rush hour: extended green light on " + $c);
    insert(n1);
    System.out.println(n1);
end


rule "Accident detected - block crossroad"
when
    Accident($c : crossroad, severity == "high")
then
    insert(new TrafficAction($c, "blockCrossroad"));
    Notification n2 = new Notification("Accident on " + $c + " – crossroad is blocked");
    insert(n2);
    System.out.println(n2);
end

rule "Pedestrian crossing - red light"
when
    PedestrianDetected($c : crossroad)
then
    insert(new TrafficAction($c, "setRedForVehicles"));
    Notification n3 = new Notification("Pedestrian detected on " + $c);
    insert(n3);
    System.out.println(n3);
end

rule "Illegal parking notification"
when
    IllegalParking($c : crossroad)
then
    Notification n4 = new Notification("Illegal parking on " + $c);
    insert(n4);
    System.out.println(n4);
end